[supervisord]
nodaemon=true 

[program:api]
command=/bin/bash -c "uvicorn api_bot:app --host 0.0.0.0 --port 8000"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/api_stdout.log
stderr_logfile=/var/log/supervisor/api_stderr.log

[program:discord_bot]
command=python bot_discord.py
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/discord_bot_stdout.log
stderr_logfile=/var/log/supervisor/discord_bot_stderr.log